# Options: [MNIST, FASHION_MNIST, CIFAR10, CIFAR100]
dataset: FASHION_MNIST

# See https://keras.io/api/losses/
loss_function_auto_encoder: mean_squared_error
loss_function_classifier: categorical_crossentropy
loss_function_supervised_classifier: categorical_crossentropy

# See https://keras.io/api/optimizers/
optimizer_autoencoder: adam
optimizer_classifier: adam
optimizer_supervised_classifier: adam

# Set to null to use the optimizer's default learning rate
learning_rate_auto_encoder: null
learning_rate_classifier: 0.01
learning_rate_supervised_classifier: null

latent_vector_size: 8

epochs_auto_encoder: 10
epochs_classifier: 20
epochs_supervised_classifier: 20

batch_size: 64

# Specifies how much of the dataset to use. Set to 1.0 to use the whole dataset
dataset_ratio: 0.2

# How we should split the dataset. Labelled vs. unlabeled data ratio
labeled_to_unlabeled_split_ratio: 0.1

# How we divide D2 (labeled data) into training-test sets, where the training
# set is further divided into training-validation sets
train_to_test_ratio: 0.8
validation_ratio: 0.2

# Whether or not to freeze the weights of the encoder module when using it in
# the classifier.
freeze: True

# Whether or not to display plots over learning curves, tSNE plots of latent
# vectors etc.
visualize: True

##### The below parameters are ignored if visualize is False

# The number of autoencoder reconstructions (and corresponding input images)
# to display at the end of the run.
auto_encoder_reconstructions: 10

# How many latent vectors to visualize in the tSNE plot
latent_vector_plot_count: 250
