# Beware of changing these parameters
training_ratio: 0.7
validation_ratio: 0.2
testing_ratio: 0.1
min_image_dimension: 10
max_image_dimension: 50

# Change these parameters as you like

# Specifies the image dimensions of a square image (i.e., n x n)
image_dimension: 10

# Adjust the size ranges to restrict the size of the figures within the n x n image
# It is best to keep the minimum range > 1 (expect for thickness)
circle_radius_range: [3, 100]
rectanlge_range_height: [3, 100]
rectanlge_range_width: [3, 100]
triangle_range: [2, 25]
cross_range_height: [2, 25]
cross_range_width: [2, 25]
cross_thickness_range: [1, 3]

images_in_each_class: 100

# Specifies the fraction of randomly-set pixels in each image.
noise_ratio: 0.010

# Whether the returned arrays should be 1D or 2D
flatten: True

# Whether the objects in the image should be centered or not
center: false
