# Length of the bitstring that changes as time moves (i.e., as the sequence progresses)
# Typically in the interval [5, 20]
pattern_length: 10

# How long one sequence should be
# Typically in the interval [3, 20]
sequence_length: 20

# How many sequences to generate (typically between 10-500)
sequences: 200

# Specifies the fraction of randomly-set pixels in each sequence.
# Do NOT use this on classification problems, only use on regression problems
noise_ratio: 0.0
